version: "3.5"

services:
  proxy:
    image: nomos.proxy:latest
    secrets:
      - proxy_fullchain_pem
      - proxy_privkey_pem
      - proxy_htpasswd
    environment:
      - SERVER_NAME=nomos.localhost
      - AUTH_BASIC_USER_FILE=/run/secrets/proxy_fullchain_pem
      - SSL_CERTIFICATE_FILE=/run/secrets/proxy_privkey_pem
      - SSL_CERTIFICATE_KEY_FILE=/run/secrets/proxy_htpasswd
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy
    depends_on:
      - visualizer
    deploy:
      placement:
        constraints: [node.role == manager]

  adminvpn:
    image: nomos.adminvpn:latest
    secrets:
      - adminvpn_password
    ports:
      - "2222:22"
    networks:
      - admin
    deploy:
      placement:
        constraints: [node.role == manager]
  
  core:
    image: nomos.core:latest
    secrets:
      - mq_vhost
      - mq_user
      - mq_password
      - db_user
      - db_password
      - db_database
      - ses_region
      - ses_clientid
      - ses_secret
      - from_email
      - oauth_github_client
      - oauth_github_secret
      - oauth_slack_client
      - oauth_slack_secret
      - oauth_slack_team
      - oauth_google_client
      - oauth_google_secret
    networks:
      data:
      app:
      proxy:
        aliases:
          - core
    depends_on:
      - rabbitmq
      - manager
    deploy:
      mode: replicated
      
  web:
    image: nomos.web:latest
    networks:
      proxy:
        aliases:
          - web
    deploy:
      mode: replicated
      
  visualizer:
    image: dockersamples/visualizer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      proxy:
        aliases:
          - nomos_visualizer
      admin:
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
          
  rabbitmq:
    image: rabbitmq
    secrets:
      - mq_vhost
      - mq_user
      - mq_password
    environment:
      - RABBITMQ_DEFAULT_VHOST_FILE=/run/secrets/mq_vhost
      - RABBITMQ_DEFAULT_USER_FILE=/run/secrets/mq_user
      - RABBITMQ_DEFAULT_PASS_FILE=/run/secrets/mq_password
    networks:
      - app
      - admin
    deploy:
      mode: replicated
      replicas: 1
          
  manager:
    image: nomos.database.manager:latest
    secrets:
      - db_root_password
      - db_user
      - db_password
      - db_database
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_USER_FILE=/run/secrets/db_user
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
      - MYSQL_DATABASE_FILE=/run/secrets/db_database
    networks:
      - data
      - admin
    depends_on:
      - master
      - replica
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
          
  master:
    image: nomos.database.master:latest
    secrets:
      - db_root_password
      - db_user
      - db_password
      - db_database
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_USER_FILE=/run/secrets/db_user
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
      - MYSQL_DATABASE_FILE=/run/secrets/db_database
    volumes:
      - "/srv/nomos/storage/master:/var/lib/mysql"
    networks:
      - data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.nomos.persistence.master == storage]
      
  replica:
    image: nomos.database.replica:latest
    secrets:
      - db_root_password
      - db_user
      - db_password
      - db_database
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_USER_FILE=/run/secrets/db_user
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
      - MYSQL_DATABASE_FILE=/run/secrets/db_database
    volumes:
      - "/srv/nomos/storage/replica:/var/lib/mysql"
    networks:
      - data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.nomos.persistence.replica == storage]
      
secrets:
  mq_vhost:
    file: ./secrets/mq_vhost
    name: mq_vhost_${npm_package_version}
  mq_user:
    file: ./secrets/mq_user
    name: mq_user_${npm_package_version}
  mq_password:
    file: ./secrets/mq_password
    name: mq_password_${npm_package_version}
  db_root_password:
    file: ./secrets/db_root_password
    name: db_root_password_${npm_package_version}
  db_user:
    file: ./secrets/db_user
    name: db_user_${npm_package_version}
  db_password:
    file: ./secrets/db_password
    name: db_password_${npm_package_version}
  db_database:
    file: ./secrets/db_database
    name: db_database_${npm_package_version}
  ses_region:
    file: ./secrets/ses_region
    name: ses_region_${npm_package_version}
  ses_clientid:
    file: ./secrets/ses_clientid
    name: ses_clientid_${npm_package_version}
  ses_secret:
    file: ./secrets/ses_secret
    name: ses_secret_${npm_package_version}
  from_email:
    file: ./secrets/from_email
    name: from_email_${npm_package_version}
  oauth_github_client:
    file: ./secrets/oauth_github_client
    name: oauth_github_client_${npm_package_version}
  oauth_github_secret:
    file: ./secrets/oauth_github_secret
    name: oauth_github_secret_${npm_package_version}
  oauth_slack_client:
    file: ./secrets/oauth_slack_client
    name: oauth_slack_client_${npm_package_version}
  oauth_slack_secret:
    file: ./secrets/oauth_slack_secret
    name: oauth_slack_secret_${npm_package_version}
  oauth_slack_team:
    file: ./secrets/oauth_slack_team
    name: oauth_slack_team_${npm_package_version}
  oauth_google_client:
    file: ./secrets/oauth_google_client
    name: oauth_google_client_${npm_package_version}
  oauth_google_secret:
    file: ./secrets/oauth_google_secret
    name: oauth_google_secret_${npm_package_version}
  proxy_fullchain_pem:
    file: ./secrets/proxy_fullchain_pem
    name: proxy_fullchain_pem_${npm_package_version}
  proxy_privkey_pem:
    file: ./secrets/proxy_privkey_pem
    name: proxy_privkey_pem_${npm_package_version}
  proxy_htpasswd:
    file: ./secrets/proxy_htpasswd
    name: proxy_htpasswd_${npm_package_version}
  adminvpn_password:
    file: ./secrets/adminvpn_password
    name: adminvpn_password_${npm_package_version}

networks:
  data:
  app:
  proxy:
    external: true
  admin:
    external: true
