version: 2.1

jobs:
  checkout:
    docker:
      - image: vanhack/nomos.build:1.0.0.0-dev
    working_directory: ~/nomos
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/nomos
      - run:
          name: Set build number version
          command: |
            echo -n ".${CIRCLE_BUILD_NUM}" > buildnum.version
      - persist_to_workspace:
          root: ~/nomos
          paths: buildnum.version
          
  build-core:
    docker:
      - image: vanhack/nomos.build:1.0.0.0-dev
    working_directory: ~/nomos
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - attach_workspace:
          at: /tmp/workspace
      - restore_cache:
          keys:
            - v1-layers-nomos.core-{{ .Branch }}
          paths:
            - /caches/nomos.core.tar
      - run: 
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/nomos.core.tar | true
      - run:
          name: Set build version
          working_directory: ~/nomos/core
          command: |
            BUILD_NUM=$(cat /tmp/workspace/buildnum.version)
            sed -ie s/.0-dev/${BUILD_NUM}/ package.json
      - run:
          name: Build nomos.core Docker image
          working_directory: ~/nomos/core
          command: |
            npm run build -- --cache-from=vanhack/nomos.core
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/nomos.core.tar vanhack/nomos.core
      - persist_to_workspace:
          root: /caches
          paths: nomos.core.tar
      - save_cache:
          key: v1-layers-nomos.core-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/nomos.core.tar
            
  test-core:
    docker:
      - image: vanhack/nomos.build:1.0.0.0-dev
    working_directory: ~/nomos
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load Docker image
          command: |
            docker load -i /tmp/workspace/nomos.core.tar
      - run:
          name: Test Docker image
          command: |
            docker run vanhack/nomos.core test

            
  push-core:
    docker:
      - image: vanhack/nomos.build:1.0.0.0-dev
    working_directory: ~/nomos
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load Docker image
          command: |
            docker load -i /tmp/workspace/nomos.core.tar
      - run:
          name: Push Docker image
          command: |
            docker push vanhack/nomos.core

  
workflows:
  version: 2
  beard:
    jobs:
      - checkout
      - build-core:
          requires:
            - checkout
      - test-core:
          requires:
            - build-core
      - push-core:
          requires:
            - test-core
          filters:
            branches:
              only: master
